In [1]:
import torch

x = torch.randn(1, 5, requires_grad=True)
y = torch.randn(5, 3, requires_grad=True)
z = torch.randn(3, 1, requires_grad=True)
print("x:\n", x, "\ny\n", y, "\nz\n", z)
xy = torch.matmul(x, y)
print("xy\n", xy)
xyz = torch.matmul(xy, z)
xyz.backward()
print(x.grad, y.grad, z.grad)

zy = torch.matmul(y, z).view(-1, 5)
print(zy)

x:
 tensor([[-0.1383, -2.0996,  1.9764,  0.7538,  0.2351]], requires_grad=True) 
y
 tensor([[ 0.2189,  0.5964,  0.5446],
        [-0.1589,  0.1482, -0.3878],
        [ 0.4116, -0.8481,  1.7844],
        [-0.2409,  0.7687, -0.7422],
        [-0.1929, -0.9839,  0.3454]], requires_grad=True) 
z
 tensor([[ 1.1003],
        [-1.0295],
        [ 0.6090]], requires_grad=True)
xy
 tensor([[ 0.8899, -1.7216,  3.7874]], grad_fn=<MmBackward0>)
tensor([[-0.0415, -0.5636,  2.4127, -1.5085,  1.0111]]) tensor([[-0.1522,  0.1424, -0.0842],
        [-2.3103,  2.1616, -1.2787],
        [ 2.1747, -2.0347,  1.2036],
        [ 0.8295, -0.7761,  0.4591],
        [ 0.2586, -0.2420,  0.1432]]) tensor([[ 0.8899],
        [-1.7216],
        [ 3.7874]])
tensor([[-0.0415, -0.5636,  2.4127, -1.5085,  1.0111]],
       grad_fn=<ViewBackward0>)
